#Global Configuration Updated
#Thu Sep 04 15:55:03 IRST 2025
allowedDifficulties=easy,medium,hard
allowedSpeeds=1,2,5,10,100,1000,10000
defaultDifficulty=medium
defaultSpeed=1
game\ speed=3
game.speed=10
game.turn.duration=30
resource.generation.interval=5
whitewalker.attack.interval=10
