#Global Configuration Updated
#Tue Sep 30 14:59:48 IRST 2025
allowedDifficulties=easy,medium,hard
allowedSpeeds=1,2,5,10,10000,1000,5000,2000
defaultDifficulty=medium
defaultSpeed=10000
game.speed=0
game.turn.duration=30
resource.generation.interval=5
whitewalker.attack.interval=10
